### ISSUE TITLE
Egg format breaks migrations

### ISSUE THREAD

**Issue by GertBurger** [dym/django-offline-messages#24]
Hi

When the package is installed via pip it places an egg file and django cannot read migrations from it.

File '...python2.7/site-packages/Django-1.7.8-py2.7.egg/django/db/migrations/loader.py", line 94, in load_disk
    for name in os.listdir(directory):
OSError: [Errno 20] Not a directory: '....python2.7/site-packages/django_offline_messages-0.3.4-py2.7.egg/offline_messages/migrations'

I suggest the zip_safe=False property is set in setup.py to bypass this.

On a side note, could we possibly also have a whl uploaded to pypi? ;P

**Comment by dym** [comment]
Hi Gert

May I ask you to provide a pull request with the necessary fixes? If you have some free time, it would be the fastest option.

Regardring whl: I'll look into what's it about, I didn't follow python development very closely for a while.

**Comment by GertBurger** [comment]
Hi

I'll make a PR in a bit.

For a whl make sure the wheel package is installed and then run 'python
setup.py bdist_wheel' and a .whl file will appear in dist/, supposedly one
can upload them to pypi in the same manner as an egg.

**Comment by GertBurger** [comment]
Thanks for merging the PR, any change you could upload a new release so that it becomes usable?

**Comment by dym** [comment]
Hi Gert
Uploaded new release. Not sure about wheel, didn't have much time to read about it

**Comment by GertBurger** [comment]
Thanks!
